module.exports = {
  darkMode: "class",
  content: [
    "./public/*.html",
    "./app/helpers/**/*.rb",
    "./app/javascript/**/*.js",
    "./app/views/**/*.{erb,haml,html,slim}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#6B3FA0",
        accent: "#D4AF37",
        cream: "#FAF7F2",
        charcoal: "#1F1F1F",
        "surface-container-highest": "#e5e2e1",
        "on-primary-fixed": "#2a0053",
        "outline-variant": "#cdc3d2",
        "inverse-primary": "#dab9ff",
        "on-tertiary-container": "#cfcbc3",
        "on-tertiary-fixed": "#1c1c17",
        "on-primary-container": "#ddbfff",
        "on-secondary-fixed-variant": "#574500",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#ffe088",
        background: "#fcf9f8",
        "on-error": "#ffffff",
        "primary-container": "#6b3fa0",
        "primary-fixed-dim": "#dab9ff",
        "tertiary-fixed-dim": "#cac6be",
        surface: "#fcf9f8",
        outline: "#7c7482",
        "on-primary": "#ffffff",
        "on-secondary-container": "#745c00",
        "on-error-container": "#93000a",
        "surface-dim": "#dcd9d9",
        "on-surface": "#1b1b1c",
        "inverse-surface": "#303030",
        "secondary-container": "#fed65b",
        "on-tertiary-fixed-variant": "#484741",
        "surface-container-low": "#f6f3f2",
        "on-surface-variant": "#4b4451",
        "inverse-on-surface": "#f3f0ef",
        "on-background": "#1b1b1c",
        "surface-bright": "#fcf9f8",
        secondary: "#735c00",
        "tertiary-fixed": "#e6e2da",
        error: "#ba1a1a",
        tertiary: "#403f39",
        "surface-container-high": "#eae7e7",
        "surface-container": "#f0eded",
        "on-primary-fixed-variant": "#5b2f90",
        "on-secondary": "#ffffff",
        "surface-variant": "#e5e2e1",
        "primary-fixed": "#eedbff",
        "secondary-fixed-dim": "#e9c349",
        "error-container": "#ffdad6",
        "surface-tint": "#7448a9",
        "surface-container-lowest": "#ffffff",
        "tertiary-container": "#585650",
        "on-secondary-fixed": "#241a00",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-md": "1rem",
        gutter: "1.5rem",
        margin: "2.5rem",
        "space-sm": "0.5rem",
        "space-lg": "1.5rem",
        "gutter-sm": "1rem",
        "space-xl": "2.5rem",
        "space-xs": "0.25rem",
        "margin-sm": "1rem",
      },
      fontFamily: {
        heading: ["Poppins", "sans-serif"],
        body: ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "display-lg": ["Epilogue", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-sm": ["Epilogue", "sans-serif"],
        "headline-xl": ["Epilogue", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-lg": ["Inter", "sans-serif"],
        "title-md": ["Epilogue", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Epilogue", "sans-serif"],
        "headline-xl-mobile": ["Epilogue", "sans-serif"],
        "headline-md": ["Epilogue", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Epilogue", "sans-serif"],
      },
      fontSize: {
        "label-sm": ["0.6875rem", { lineHeight: "0.875rem", letterSpacing: "0.04em", fontWeight: "600" }],
        "display-lg": ["3.5rem", { lineHeight: "4rem", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["1.125rem", { lineHeight: "1.75rem", fontWeight: "400" }],
        "headline-sm": ["1.25rem", { lineHeight: "1.75rem", fontWeight: "600" }],
        "headline-xl": ["2.5rem", { lineHeight: "3rem", letterSpacing: "-0.015em", fontWeight: "600" }],
        "label-md": ["0.75rem", { lineHeight: "1rem", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-lg": ["0.875rem", { lineHeight: "1.25rem", letterSpacing: "0.01em", fontWeight: "600" }],
        "title-md": ["1.125rem", { lineHeight: "1.5rem", fontWeight: "500" }],
        "body-md": ["1rem", { lineHeight: "1.5rem", fontWeight: "400" }],
        "headline-lg": ["2rem", { lineHeight: "2.5rem", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-xl-mobile": ["1.75rem", { lineHeight: "2.25rem", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["1.5rem", { lineHeight: "2rem", fontWeight: "600" }],
        "body-sm": ["0.875rem", { lineHeight: "1.25rem", fontWeight: "400" }],
        "display-lg-mobile": ["2.25rem", { lineHeight: "2.75rem", letterSpacing: "-0.01em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
